name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    
    - name: Publish
      run: dotnet publish -c Release -o '${{ github.workspace }}/out'
    
    - name: Zip
      run:
        cd '${{ github.workspace }}/out'
        zip -r ${{ github.workspace }}/out.zip *
        
    - name: Deploy to AWS
      uses: einaregilsson/beanstalk-deploy@v13
      with:
        aws_access_key: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        application_name: testeapp
        environment_name: testeapp-dev
        region: us-east-1
        version_label: ${{ github.run_id }}
        version_description: ${{ github.sha }}
        deployment_package: ${{ github.workspace }}/out.zip
